### ISSUE TITLE
ACE05 dataset not in unified?

### ISSUE THREAD

**Issue by MarvinT** [LorrinWWW/two-are-better-than-one#11]
just trying to run the default parameters provided by the readme.md and its crashing with this error:
```
File "gens/gen_bert.py", line 257, in <module>
    with open(f'./datasets/unified/train.{flag}.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: './datasets/unified/train.ACE05.json'
```
should I try a different dataset?

**Comment by LorrinWWW** [comment]
ACE has copyright issues, so we cannot release the preprocessed datasets here. 
You may have to use the scripts provided by us to preprocess the raw corpus by yourself.
