### ISSUE TITLE
Issue with running the code due to dimension mismatch

### ISSUE THREAD

**Issue by arijitatiitkgp** [LorrinWWW/two-are-better-than-one#12]
I have generated the contextual embedding by the below code-
python gens/gen_bert.py \
    --model_name  bert-base-multilingual-cased \
    --dataset <dataset name> \
    --save_path ./wv/<contextual embedding file>

But when running the train script by below code facing the issue-
python -u train.py \
    --num_layers 3 \
    --batch_size 24 \
    --evaluate_interval 500 \
    --dataset <Dataset Name> \
    --max_epoches 5000 \
    --max_steps 20000 \
    --model_class JointModel  \
    --model_write_ckpt ./ckpts/my_model \
    --crf None \
    --optimizer adam \
    --lr 0.001 \
    --tag_form iob2 \
    --cased 0 \
    --token_emb_dim 100 \
    --char_emb_dim 30 \
    --char_encoder lstm \
    --lm_emb_dim 4096 \
    --head_emb_dim 768 \
    --lm_emb_path ./wv/<contextual embedding file>
    --hidden_dim 200 \
    --ner_tag_vocab_size <2*nertag+2> \
    --re_tag_vocab_size <2*re_tag+2> \
    --vocab_size 15000 \
    --dropout 0.5 \
    --grad_period 1

Can you tell me what should be the correct parameter value to run the code with custom data and contextual embeddings?

**Comment by LorrinWWW** [comment]
You are using bert-base models, whose hidden size (d) is 768, number of attention head (h) is 12, number of layers (l) is 12. So lm_emb_dim should be d\*4=3072 (we concatenate last four layers by default), and head_emb_dim should be h\*l=144.

---

Correction: lm_emb_dim should be d=768, and head_emb_dim should be h\*l=144.

**Comment by arijitatiitkgp** [comment]
Thanks for the clarification but while trying with below-
python -u train.py \
    --num_layers 3 \
    --batch_size 24 \
    --evaluate_interval 500 \
    --dataset <dataset name> \
    --max_epoches 5000 \
    --max_steps 20000 \
    --model_class JointModel  \
    --model_write_ckpt ./ckpts/my_model \
    --crf None \
    --optimizer adam \
    --lr 0.001 \
    --tag_form iob2 \
    --cased 0 \
    --token_emb_dim 100 \
    --char_emb_dim 30 \
    --char_encoder lstm \
    --lm_emb_dim 3072 \
    --head_emb_dim 144 \
    --lm_emb_path ./wv/mbert.bert_with_heads.pkl \
    --hidden_dim 200 \
    --ner_tag_vocab_size 40 \
    --re_tag_vocab_size 104 \
    --vocab_size 15000 \
    --dropout 0.5 \
    --grad_period 1

getting the below error-
2021-05-23 17:58:08.175617: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
/usr/local/lib/python3.7/dist-packages/torch/nn/modules/rnn.py:61: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.5 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
reading data..
=== start training ===
warm up: learning rate was adjusted to 1e-06
Traceback (most recent call last):
  File "train.py", line 249, in <module>
    trainer.train_model(args=args)
  File "/content/two-are-better-than-one/data/base.py", line 73, in train_model
    loss = model.train_step(batch)['loss'].detach().cpu().numpy()
  File "/content/two-are-better-than-one/models/base.py", line 110, in hooked_train_step
    rets = self._train_step(inputs)
  File "/content/two-are-better-than-one/models/joint_models.py", line 514, in train_step
    rets = self(inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/two-are-better-than-one/models/joint_models.py", line 346, in forward
    rets = self.forward_step(inputs)
  File "/content/two-are-better-than-one/models/joint_models.py", line 328, in forward_step
    inputs = self.forward_embeddings(inputs)
  File "/content/two-are-better-than-one/models/joint_models.py", line 293, in forward_embeddings
    embeddings = self.reduce_emb_dim(embeddings)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0

**Comment by LorrinWWW** [comment]
Oh sorry I remembered it wrong, the hidden size does not need to be multiplied by 4 (We use mean rather than concatenation), i.e., "lm_emb_dim" should be 768.

If still not work, you can try to disable attention head embeddings (by setting "head_emb_dim" to be 0) or both attention head and contextualized embeddings (by setting both "head_emb_dim" and "lm_emb_dim" to be 0), to see which part raises the error.
