### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by LimKim** [LorrinWWW/two-are-better-than-one#13]
=== start training ===
warm up: learning rate was adjusted to 1e-06
Traceback (most recent call last):
  File "train.py", line 249, in <module>
    trainer.train_model(args=args)
  File "/mnt/lustre02/jiangsu/aispeech/home/yfy19/remote/knowledge_factory/two-are-better-than-one/data/base.py", line 73, in train_model
    loss = model.train_step(batch)['loss'].detach().cpu().numpy()
  File "/mnt/lustre02/jiangsu/aispeech/home/yfy19/remote/knowledge_factory/two-are-better-than-one/models/base.py", line 110, in hooked_train_step
    rets = self._train_step(inputs)
  File "/mnt/lustre02/jiangsu/aispeech/home/yfy19/remote/knowledge_factory/two-are-better-than-one/models/joint_models.py", line 516, in train_step
    loss.backward()
  File "/mnt/lustre02/jiangsu/aispeech/home/yfy19/.conda/envs/torch_env_clone/lib/python3.6/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/mnt/lustre02/jiangsu/aispeech/home/yfy19/.conda/envs/torch_env_clone/lib/python3.6/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 2)

**Comment by LimKim** [comment]
python -u train.py \
    --num_layers 3 \
    --batch_size 8 \
    --evaluate_interval 500 \
    --dataset CoNLL04 \
    --pretrained_wv ./wv/glove.6B.100d.ace05.txt  \
    --max_epoches 5000 \
    --max_steps 20000 \
    --model_class JointModel  \
    --model_write_ckpt ./ckpts/my_model \
    --crf None \
    --optimizer adam \
    --lr 0.001 \
    --tag_form iob2 \
    --cased 0 \
    --token_emb_dim 100 \
    --char_emb_dim 30 \
    --char_encoder lstm \
    --lm_emb_dim 768 \
    --head_emb_dim 144 \
    --lm_emb_path ./wv/bert.CoNLL04_with_heads.pkl \
    --hidden_dim 200 \
    --ner_tag_vocab_size 32 \
    --re_tag_vocab_size 64 \
    --vocab_size 15000 \
    --dropout 0.5 \
    --grad_period 1

**Comment by LorrinWWW** [comment]
Can you comment out all "@jit.script_method" in "./layers/encodings/mdrnns/gru.py" and re-run the training script for a clearer log?

**Comment by LimKim** [comment]
> Can you comment out all "@jit.script_method" in "./layers/encodings/mdrnns/gru.py" and re-run the training script for a clearer log?

Sry for asking this question :).
I found my pytorch version is 1.6.0, so i have solved the above problem.
But when i re-run the code, another problem appeared.
I post the problem below:
"""""""""
UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)
Segmentation fault
"""""""""

I browsed other people’s questions, and someone had the same problem, but she thought it was a problem of the allennlp version.
This is also what makes me strange, because the author you said in other issue that you can even comment out all code about allennlp.
I did comment it out because I didn’t use crf.

**Comment by LorrinWWW** [comment]
Sorry, but I still cannot reproduce the error. 
It is usually hard to debug on GPU (sometimes it just raises a segmentation fault), and I would recommend to run on CPU, which often shows richer log info.

From my perspective, I guess it would be (array) index out of bounds, e.g., the word vocab size is smaller than the model tries to index.

**Comment by LorrinWWW** [comment]
Oh well, I found you use word vectors of ace05 on conll04 dataset ("--pretrained_wv ./wv/glove.6B.100d.ace05.txt"), which will be harmful to the performance since their vocab are different. Besides, conll04 may have a larger vocab size, so you may have to enlarge "--vocab_size" to avoid (array) index out of bounds error.

**Comment by LimKim** [comment]
> Oh well, I found you use word vectors of ace05 on conll04 dataset ("--pretrained_wv ./wv/glove.6B.100d.ace05.txt"), which will be harmful to the performance since their vocab are different. Besides, conll04 may have a larger vocab size, so you may have to enlarge "--vocab_size" to avoid (array) index out of bounds error.

Thank you very much!!
I can run it now.
One more question, if i want to train model in my own dataset, do i need to train w2v on my dataset first and replace the w2v path with mine?

**Comment by LorrinWWW** [comment]
No, you don't have to. "./wv/glove.6B.100d.ace05.txt" and "./wv/glove.6B.100d.conll04.txt" are simply subsets of glove 6B 100d vectors. The purpose is to reduce the memory usage and to accelerate training (a bit).
If memory is enough, you can use the original glove vectors and set "--vocab_size 400100". 
And you can also train and use your own w2v without any problem.

**Comment by LimKim** [comment]
> No, you don't have to. "./wv/glove.6B.100d.ace05.txt" and "./wv/glove.6B.100d.conll04.txt" are simply subsets of glove 6B 100d vectors. The purpose is to reduce the memory usage and to accelerate training (a bit).
> If memory is enough, you can use the original glove vectors and set "--vocab_size 400100".
> And you can also train and use your own w2v without any problem.

I see, thank you very much!
