### ISSUE TITLE
On the evaluation of ACE

### ISSUE THREAD

**Issue by Ber666** [LorrinWWW/two-are-better-than-one#14]
> Follow Li and Ji (2014); Miwa and Bansal (2016), we use head spans for entities in ACE. And we keep the full mention boundary for other corpora.

In Li and Ji (2014), 
> An entity mention is considered correct if its entity type is correct and the offsets of its mention head are correct. A relation mention is considered correct if its relation type is correct, and the head offsets of two entity mention arguments are both correct.

It seems that the evaluation code in this repo considers the full mention boundary instead of head spans. How did you get the result on ACE dataset?

**Comment by LorrinWWW** [comment]
We follow the previous work and adapt from their preprocessing scripts.
Specifically for ACE, we just regard head spans as full mentions (this is done during preprocessing), and thus an entity mention prediction is correct if its entity type is correct and the boundary is correct, which should be in line with Li and Ji (2014).

But there do exist incorrect comparisons in the literature, and you may want to read this paper: [Let’s Stop Incorrect Comparisons in End-to-end Relation Extraction!](https://aclanthology.org/2020.emnlp-main.301/)

**Comment by Ber666** [comment]
> We follow the previous work and adapt from their preprocessing scripts.
> Specifically for ACE, we just regard head spans as full mentions (this is done during preprocessing), and thus an entity mention prediction is correct if its entity type is correct and the boundary is correct, which should be in line with Li and Ji (2014).
> 
> But there do exist incorrect comparisons in the literature, and you may want to read this paper: [Let’s Stop Incorrect Comparisons in End-to-end Relation Extraction!](https://aclanthology.org/2020.emnlp-main.301/)

Thanks a lot!
