### ISSUE TITLE
Question about ACE2004

### ISSUE THREAD

**Issue by SihengLi99** [LorrinWWW/two-are-better-than-one#17]
Hello,

This work is very interesting!
However, I can not find the code about how you do the k-fold cross-validation in ACE2004.

Siheng

**Comment by LorrinWWW** [comment]
You can check the script under "./datasets/ace2004". 
Specifically, I think the k-fold splits can be found at "./datasets/ace2004/split/", which follows the way DyGIE did, https://github.com/luanyi/DyGIE/tree/master/preprocessing/ace2004/split.
