### ISSUE TITLE
obtain RE(gold) for other datasets

### ISSUE THREAD

**Issue by yyzhuang1991** [LorrinWWW/two-are-better-than-one#18]
Hi, 
   I just wonder how to obtain results of RE(gold) in Table 3 of your paper for other datasets (like CoNLL04 and ADE).  Could you help me with this? Thank you in advance.

**Comment by yyzhuang1991** [comment]
Is it just to uncomment the line "relation_preds = self._postprocess_relations(relation_logits, rets['entities']) # use GOLD entity spans" in joint_models.py? Just want to make sure that there are no other things to change.

**Comment by LorrinWWW** [comment]
Yes, to use gold entities for relation extraction just uncomment "relation_preds = self._postprocess_relations(relation_logits, rets['entities']) # use GOLD entity spans", and then comment "relation_preds = self._postprocess_relations(re_tag_logits, entity_preds)"

**Comment by yyzhuang1991** [comment]
Thank you!
