### ISSUE TITLE
data

### ISSUE THREAD

**Issue by Smile-L-up** [LorrinWWW/two-are-better-than-one#19]
Hello, in order to better study, can you put some sample data

**Comment by LorrinWWW** [comment]
The preprocessed datasets of CoNLL04 and ADE can be found at "./datasets/unified".

**Comment by Smile-L-up** [comment]
Thanks for your reply, I would like to ask, is it possible to use a script that processes ace04 data to process CoNLL04 or ADE into model input data?

**Comment by LorrinWWW** [comment]
The data has been preprocessed into the model's input format. You can directly use them for training.
