### ISSUE TITLE
ckpts

### ISSUE THREAD

**Issue by zhouluo07** [LorrinWWW/two-are-better-than-one#20]
Hello, I met this problem while running this code:
"[Errno 2] No such file or directory: './ckpts/my_model.pt'".
 I don‘t know to solve it. Looking forward to hearing from you.

**Comment by LorrinWWW** [comment]
Thanks for reporting this. I will look into it. 
My first guess is that it's due to the missing of folder "./ckpts/". 
Could you execute "$ mkdir ./ckpts" and try again?

**Comment by zhouluo07** [comment]
Thank you for your answer！ I will add this folder to try again.

**Comment by hhhhhh45** [comment]
> Thank you for your answer！ I will add this folder to try again.

Hello, I encountered "java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP text/*.split.txt " when I run run.zsh . I don`t know how to solve it. Have you encountered this problem?
