### ISSUE TITLE
ACE05data

### ISSUE THREAD

**Issue by hhhhhh45** [LorrinWWW/two-are-better-than-one#22]
Can I get the format of the sample data please? I want to train ace05 model, but I encountered “java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP text/*.split.txt ” when I run run.zsh . For example ,the format of the sample data is a json list and its key are tokens、sentence and so on .

**Comment by LorrinWWW** [comment]
The preprocessed datasets of CoNLL04 and ADE can be found at "./datasets/unified".
Regarding the error, please make sure you are using zsh to run the script, and use the correct version of stanford tools.

**Comment by hhhhhh45** [comment]
Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LorrinWWW/two-are-better-than-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LorrinWWW/two-are-better-than-one] ACE05data (Issue #22)





 
The preprocessed datasets of CoNLL04 and ADE can be found at "./datasets/unified".
 Regarding the error, please make sure you are using zsh to run the script, and use the correct version of stanford tools.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hhhhhh45** [comment]
Excuse me，I used stanford-corenlp-full-2015-04-20 and&nbsp;stanford-postagger-2015-04-20 . And I used zsh to run run.zsh . I still get "java.lang.ClassNotFoundException: edu.stanford.nlp.pipeline.StanfordCoreNLP" , I don`t know how to solve it . Could you help me please?


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "LorrinWWW/two-are-better-than-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LorrinWWW/two-are-better-than-one] ACE05data (Issue #22)





 
The preprocessed datasets of CoNLL04 and ADE can be found at "./datasets/unified".
 Regarding the error, please make sure you are using zsh to run the script, and use the correct version of stanford tools.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hhhhhh45** [comment]
Excuse me，I found it is a path problem. Thank you ! And after I changed path, I found this 

&nbsp;.I have doubts about the train_list ，whether its type of content is txt or ann. Could you help me please?



------------------ 原始邮件 ------------------
发件人:                                                                                                                        "LorrinWWW/two-are-better-than-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LorrinWWW/two-are-better-than-one] ACE05data (Issue #22)





 
The preprocessed datasets of CoNLL04 and ADE can be found at "./datasets/unified".
 Regarding the error, please make sure you are using zsh to run the script, and use the correct version of stanford tools.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hhhhhh45** [comment]
Excuse me，I am so sorry.


Is this code the one that generates the txt and ann files?


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "LorrinWWW/two-are-better-than-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LorrinWWW/two-are-better-than-one] ACE05data (Issue #22)





 
The preprocessed datasets of CoNLL04 and ADE can be found at "./datasets/unified".
 Regarding the error, please make sure you are using zsh to run the script, and use the correct version of stanford tools.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hhhhhh45** [comment]
Excuse me，I am so sorry. I don`t why I run below code ,then I get a null file. Could you help me please?&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "LorrinWWW/two-are-better-than-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LorrinWWW/two-are-better-than-one] ACE05data (Issue #22)





 
The preprocessed datasets of CoNLL04 and ADE can be found at "./datasets/unified".
 Regarding the error, please make sure you are using zsh to run the script, and use the correct version of stanford tools.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hhhhhh45** [comment]
I'm sorry to bother you again. Is the following form the correct form to enter?







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "LorrinWWW/two-are-better-than-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月8日(星期二) 下午3:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LorrinWWW/two-are-better-than-one] ACE05data (Issue #22)





 
The preprocessed datasets of CoNLL04 and ADE can be found at "./datasets/unified".
 Regarding the error, please make sure you are using zsh to run the script, and use the correct version of stanford tools.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LorrinWWW** [comment]
Sorry but I cannot see the code you posted.
Do you know which step in run.zsh yields null files?

**Comment by LorrinWWW** [comment]
Fyi, this preprocessing code is adapted from DyGIE (https://github.com/luanyi/DyGIE/tree/master/preprocessing). 
You can also check if their scripts work or not.

**Comment by hhhhhh45** [comment]
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LorrinWWW/two-are-better-than-one"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月10日(星期四) 上午9:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LorrinWWW/two-are-better-than-one] ACE05data (Issue #22)





 
Fyi, this preprocessing code is adapted from DyGIE (https://github.com/luanyi/DyGIE/tree/master/preprocessing).
 You can also check if their scripts work or not.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
