### ISSUE TITLE
epoch

### ISSUE THREAD

**Issue by zhouluo07** [LorrinWWW/two-are-better-than-one#24]
Hello, when I learn and run your code, the results show only steps. 
"g_step 2000, step 152, avg_time 0.874, loss:51.5502"
I don't know how to use epoch in this code. And I have difficulty in understanding the relationship between the epoch and step and definitions of them both in this code. Looking forward to your answer. Thank you very much.

**Comment by LorrinWWW** [comment]
A "step" means a forward and backward pass during training.

An "epoch" means an iteration over the entire dataset.

For example, if a dataset contains 20,000 samples and the batch size is 100, then a step will compute the loss on 100 samples, and an epoch will consist of 200 steps.

**Comment by zhouluo07** [comment]
> A "step" means a forward and backward pass during training.
> 
> An "epoch" means an iteration over the entire dataset.
> 
> For example, if a dataset contains 20,000 samples and the batch size is 100, then a step will compute the loss on 100 samples, and an epoch will consist of 200 steps.

Thank you for your reply. I guess I didn't understand the problem before because I didn't understand the meaning of the "global steps" argument. So in this code, can I understand this question as following?

global steps = epoches * (the size of dataset) / batchsize + steps,

where "global steps" means the number of global steps, "epoches" means the number of epoches, “steps" means the number of steps in the result of the last run.

**Comment by LorrinWWW** [comment]
> > A "step" means a forward and backward pass during training.
> > An "epoch" means an iteration over the entire dataset.
> > For example, if a dataset contains 20,000 samples and the batch size is 100, then a step will compute the loss on 100 samples, and an epoch will consist of 200 steps.
> 
> Thank you for your reply. I guess I didn't understand the problem before because I didn't understand the meaning of the "global steps" argument. So in this code, can I understand this question as following?
> 
> global steps = epoches * (the size of dataset) / batchsize + steps,
> 
> where "global steps" means the number of global steps, "epoches" means the number of epoches, “steps" means the number of steps in the result of the last run.

Yes :)

**Comment by zhouluo07** [comment]
> > > A "step" means a forward and backward pass during training.
> > > An "epoch" means an iteration over the entire dataset.
> > > For example, if a dataset contains 20,000 samples and the batch size is 100, then a step will compute the loss on 100 samples, and an epoch will consist of 200 steps.
> > 
> > 
> > Thank you for your reply. I guess I didn't understand the problem before because I didn't understand the meaning of the "global steps" argument. So in this code, can I understand this question as following?
> > global steps = epoches * (the size of dataset) / batchsize + steps,
> > where "global steps" means the number of global steps, "epoches" means the number of epoches, “steps" means the number of steps in the result of the last run.
> 
> Yes :)

Okay, I get it. Thank you very much!
