### ISSUE TITLE
中文迁移问题

### ISSUE THREAD

**Issue by noWay2DeBug** [LorrinWWW/two-are-better-than-one#25]
您好！在看了您的论文之后在考虑，该模型是否可以input部分（论文中S0）替换为中文词嵌入模型直接进行词嵌入从而来处理中文的关系抽取任务？

**Comment by LorrinWWW** [comment]
直觉上改为中文嵌入是可行的，不过我们暂时还未在中文数据集上进行测试，所以不清楚具体效果会怎么样

**Comment by noWay2DeBug** [comment]
感谢您的回复！祝假期快乐

**Comment by noWay2DeBug** [comment]
很抱歉再次打扰您，想继续关于您在[#10](https://github.com/LorrinWWW/two-are-better-than-one/issues/10)所说：
> 目前的实现没有考虑嵌套实体和多标签的情况，需要剔除这些数据。


所谓的多标签是指 两个实体对应多个标签，还是说 同一个语句的多个实体关系（实体没有重叠）也没有考虑呢？
就是任务中出现多个实体关系但实体不重叠，模型能具备良好的效果嘛？

**Comment by LorrinWWW** [comment]
* 多标签指两个实体对应多个标签：例如mention A和mention B存在某种relation C，则我们假设mention A和mention B不会存在C以外的其他关系
* 一个句子中可以出现多个实体关系，只要实体不重叠

**Comment by noWay2DeBug** [comment]
再次感谢您的回复！
