### ISSUE TITLE
shared parameters

### ISSUE THREAD

**Issue by zhouluo07** [LorrinWWW/two-are-better-than-one#26]
Hello, I have encountered a problem in the encoders whether to share parameters on the impact of the experiment results. I don't know how to run this. Could you help me? Looking forward to your reply.

**Comment by LorrinWWW** [comment]
I think you can rewrite the following code
https://github.com/LorrinWWW/two-are-better-than-one/blob/b09a0f9fb1dff1ef6d4f4ade005099488e3b8111/models/joint_models.py#L193-L201
into
```python
self.layer0 = TwoWayEncoding(
    self.config, n_heads=n_heads, first=False, direction=direction,
)
        
self.layers = nn.ModuleList([
    self.layer0 for i in range(self.depth-1)
])
```
to achieve that.

Btw, may I ask if you have any specific reason to share the parameters? It would not help reduce the memory usage as the intermediate activations account for the majority of memory occupation during training.

**Comment by zhouluo07** [comment]
Thank you for your reply. I understand it now. I want to run to analyze the relationship between this factor and the performance of results, and maybe can learn and come up with some new ideas.
