### ISSUE TITLE
allennlp的版本

### ISSUE THREAD

**Issue by fengdoudou1895** [LorrinWWW/two-are-better-than-one#3]
代码里用到了allennlp，但是readme.md里面没有写，安装最新版本的allennlp会导致装pytorch1.7，可是readme.md里要求的pytorch是１.4。所以请问allennlp的版本是多少呢

**Comment by LorrinWWW** [comment]
代码应该只有CRF部分依赖了allennlp的实现，我安装的版本是0.9.0。
不过paper里其实没有用到CRF，所以应该什么版本都没有什么影响（把allennlp相关的注释掉都行）。
