### ISSUE TITLE
数据集预处理报错

### ISSUE THREAD

**Issue by sataliulan** [LorrinWWW/two-are-better-than-one#7]
你好，感谢分享。
我依照说明文档使用ace数据集预处理脚本ace2005/run.zsh处理ace2005官方数据集（ldc2006t06）时，发现总是会报文件缺失错误，如截图所示
![截图录屏_deepin-terminal_20210222164526](https://user-images.githubusercontent.com/6769310/108684055-567ddf80-752d-11eb-8a11-ee1242390de3.png)

而奇怪的是却可以在ace2005/corpus/test 目录下发现AFP_ENG_20030304.0250.txt文件，请问是否是源数据缺损引起，亦或是有其他原因

**Comment by LorrinWWW** [comment]
我这里似乎没有遇到这个问题。这个问题是运行了一段时间（比如2分钟后）出现的还是一开始就出现的？
可以尝试检查一下文件的位置是否放置正确？例如 ace2005/English 应该是 non-empty 的。

**Comment by sataliulan** [comment]
ace2005/English目录包含了bc bn cts nw un wl 6个文件夹；感觉是运行了几秒后报错，从日志来看至少运行了5秒。我按照readme 先将ace_2005_td_v7/data/English拷贝至ace2005 后，cd ace2005, 而后在运行 run.zsh一段时间后就出现了上述问题

**Comment by sataliulan** [comment]
再次运行后发现在报上诉错误之前，会出现如下错误（如截图），我看到ace2005/text目录下全是*txt.conll文件（共599个），没有类似*.split.txt的文件，请问该种类文件是不是运行某个脚本生成的？
![截图录屏_选择区域_20210222175547](https://user-images.githubusercontent.com/6769310/108692099-2c311f80-7537-11eb-8959-64b8048e91fd.png)

**Comment by LorrinWWW** [comment]
\*.split.txt在这个步骤没有生成不正常
\*.txt.conll确实是599个，不过需要确认以下里面是不是空的
手动运行以下代码可以生成\*.split.txt吗？
```sh
# run at ./datasets/ace2005/
for i in text/*.conll
do
    python3 ../common/conll2txt.py $i >! text/`basename $i .txt.conll`.split.txt
done
```

**Comment by sataliulan** [comment]
...问题解决，bash改zsh就ok了，汗。。。
