### ISSUE TITLE
Baseline 训练问题

### ISSUE THREAD

**Issue by sataliulan** [LorrinWWW/two-are-better-than-one#8]
我看到训练参数中有crf选项，想问下若是在原有的模型上添加crf是不是将crf参数后设置对应crf 模型文件即可？

**Comment by LorrinWWW** [comment]
在我这边用你的命令训练是正常的。
看起来是有些变量没有传给gpu，也许可以尝试打印一下相关变量，看看是从哪里开始出了问题？
另外还可以尝试手动设置"--device cuda:0"。

由于报错的是在character embedding这边，建议看以下变量的device
https://github.com/LorrinWWW/two-are-better-than-one/blob/72ef43eca7ea7559e4fe0ed4635657fb856e354b/layers/encodings/embeddings.py#L157
https://github.com/LorrinWWW/two-are-better-than-one/blob/72ef43eca7ea7559e4fe0ed4635657fb856e354b/layers/encodings/embeddings.py#L173-L174

**Comment by sataliulan** [comment]
ok,thank you. 我调试时发现上述命令在cpu下正常运行，只是在gpu中报错

**Comment by LorrinWWW** [comment]
#9 也报告了同样的现象。
> On pytorch 1.4.0, 'pack_padded_sequence(input, lengths, batch_first)' can receive 'lengths' argument from cuda devices (I guess pytorch moves it to cpu internally); while on pytorch 1.7.1, 'lengths' can only be at cpu.

主要是pytorch的版本的兼容问题。现在已经修复，pull最新的代码应该可以运行了。

感谢报告错误！
