### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by CJPJ007** [LorrinWWW/two-are-better-than-one#9]
Can you please tell  how can I perform inference and get (entity, relation, entity) type of output?

**Comment by LorrinWWW** [comment]
First load the trained model:
```python
model = JointModel.load(ckpt_path)
```

Then get the prediction of an input batch:
```python
inputs = {'tokens': [['hello', 'world', '!'], ]}
rets = model.predict_step(inputs)
print(rets['entity_preds']) 
# > list of (batch-wise) list of (sentence-wise)
# (position_start, position_end, entity_type)
print(rets['relation_preds']) 
# > list of (batch-wise) list of (sentence-wise)
# (position_start_of_entity_a, position_end_of_entity_a, 
#  position_start_of_entity_b, position_end_of_entity_b, relation_type)
```

**Comment by CJPJ007** [comment]
Ok Thank You So Much.

**Comment by CJPJ007** [comment]
Are weights available for this model?

**Comment by CJPJ007** [comment]
![Screenshot (163)](https://user-images.githubusercontent.com/45278375/109418263-79a50500-79ed-11eb-9f0f-07374901bf58.png)
I am getting this error while training in Google Colaboratory.

**Comment by LorrinWWW** [comment]
Weird, that's the second issue on this, but every thing goes fine on my machine. What kind of version of pytorch you are using?

---

Figured out. On pytorch 1.4.0, 'pack_padded_sequence(input, lengths, batch_first)' can receive 'lengths' argument from cuda devices (I guess pytorch moves it to cpu internally); while on pytorch 1.7.1, 'lengths' can only be at cpu.

I will fix this quickly. Thanks for reporting the issue!

**Comment by CJPJ007** [comment]
Thank you so much. Started training.

**Comment by CJPJ007** [comment]
![Screenshot (165)](https://user-images.githubusercontent.com/45278375/109467636-7f542680-7a91-11eb-986c-27e9864a35a1.png)
I am getting this error after I perform inference.

**Comment by LorrinWWW** [comment]
This happens because BERT embeddings are pre-computed before training (through "./gens/gen_bert.py") and your input sample has not been cached. 
To perform inference on custom input text, you should pass a *transformers* checkpoint name to "--lm_emb_path", and the path of original (rather than the reduced one) glove wv to "--pretrained_wv". See #4 for more details and explanations.

**Comment by CJPJ007** [comment]
So I need to pass the tensors for those words along with words. If I am not wrong. Can you please explain something more briefly?

**Comment by LorrinWWW** [comment]
For training, we shall use the following example:
```bash
python -u train.py \
    --pretrained_wv ./wv/glove.6B.100d.ace05.txt  \ # <== we discard words that do not appear at ACE05
    --lm_emb_path ./wv/albert.ace05_with_heads.pkl \ # <== pre-computed albert embeddings, only for sentences in ACE05
    --other_arguments ...
```
In this case, input text can only be those that **exactly** appear at ACE05.

To allow inference on custom text, we recommend to modify from the following example:
```bash
python -u train.py \
    --pretrained_wv ./wv/glove.6B.100d.txt  \ # <== original GloVe file, containing all 400,000 words (need to download manually)
    --lm_emb_path albert-xxlarge-v1 \ # <== load albert model to gpu to generate contextualized word embeddings online
    --other_arguments ...
```
In this case, training will be painfully slow and memory-consuming. But it supports inference on custom input text.

You can train the model with the first example (as it is faster and requires less memory), and load that model and play with it using the second example. (\*\*I thought about it again, and loading from differently configured checkpoint may be not very straightforward. I shall modify the relevant code in the next few days.)

**Comment by CJPJ007** [comment]
Thank you so much. Thanks for that.

**Comment by LorrinWWW** [comment]
I have added a jupyter notebook ("./inference.ipynb") to show how to predict on custom text. 
Don't hesitate to tell me if you find any thing wrong or difficult to understand.

**Comment by CJPJ007** [comment]
Sure. Thanks for that.

**Comment by CJPJ007** [comment]
I tried to preform inference. Got results but those results are completely different than output mentioned in the notebook. Is it because I have trained model on ADE Dataset?

**Comment by LorrinWWW** [comment]
Yes. ADE dataset is constructed from medical reports that describe the adverse effects arising from drug use. It only contains a single relation type “Adverse-Effect” and the two entity types “Adverse-Effect” and “Drug”, which is however totally different from ACE04/05 (newswire).

**Comment by CJPJ007** [comment]
Ok Thanks for the information. As ACE2005 and ACE2004 are not publicly available datasets. Is there any other dataset that can be used or if you could share weights of trained model?

**Comment by LorrinWWW** [comment]
You can use CoNLL04, which is also a commonly used benchmark dataset. Releasing model weights may involve some other work, which may be scheduled in the near future.

**Comment by CJPJ007** [comment]
Ok Thank you so much for the information.
